trigger:
- main

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

pool: 'robbaleDevPool2'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

# New .NET Core CLI build task
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '--configuration $(buildConfiguration)'

# Run tests using .NET CLI
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    publishTestResults: true
    testRunTitle: 'Unit Tests'

# Step 5: Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# Step 6: Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: '6524f742-9360-47a4-a59d-d1e2a5d36277'
    appName: 'yared'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'